title: "Awesome GitHub Job Boards"
description: "Community-driven technology job boards hosted on GitHub."
url: "https://openings-dev.github.io"
baseurl: "/awesome-github-job-boards"
repository: "openings-dev/awesome-github-job-boards"
plugins:
  - jekyll-seo-tag
markdown: "kramdown"
kramdown:
  input: GFM
exclude:
  - node_modules
  - vendor
  - test
  - scripts
  - src
  - docs
  - Gemfile
  - Gemfile.lock
